name:                part000-understanding-parser-combinator
version:             0.1.0.0
github:              "diaspogift/part000-understanding-parser-combinator"
license:             BSD3
author:              "Fotio Manfo Felicien"
maintainer:          "felicien.fotiomanfo@gmail.com"
copyright:           "open source"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/diaspogift/part000-understanding-parser-combinator#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  part000-understanding-parser-combinator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - part000-understanding-parser-combinator

tests:
  part000-understanding-parser-combinator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - part000-understanding-parser-combinator
